version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      SQLITE_DATABASE: nextcloud.db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud
    ports:
      - 8080:80
    networks:
      - nextcloud

  dotnet-microservice:
    build: .
    container_name: dotnet-microservice
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 9080:8080
    networks:
      - nextcloud

networks:
  nextcloud:
