version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      SQLITE_DATABASE: nextcloud.db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud
    ports:
      - 8080:80
    volumes:
      # Windows notation: https://nagachiang.github.io/docker-bind-to-docker-socket-on-windows-host-from-linux-containers/
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - nextcloud

  dotnet-microservice:
    build: .
    container_name: dotnet-microservice
    environment:
      NextcloudUrl: http://nextcloud
      NextcloudSecret: 12345
    ports:
      - 9080:8080
    networks:
      - nextcloud

networks:
  nextcloud:
