auth_enabled: false

server:
  http_listen_port: 3200
  log_level: warn

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

storage:
  trace:
    backend: s3
    s3:
      bucket: monitoring
      endpoint: minio:9000
      access_key: monitoring
      secret_key: supersecret
      insecure: true
    wal:
        path: /tmp/tempo/wal

usage_report:
  reporting_enabled: false
