auth_enabled: false

server:
  http_listen_port: 3100
  log_level: warn

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-09-07
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /data/index
    cache_location: /data/cache
    cache_ttl: 168h
  aws:
    s3: http://monitoring:supersecret@minio:9000/monitoring
    s3forcepathstyle: true

limits_config:
  split_queries_by_interval: 24h
  retention_period: 90d

compactor:
  working_directory: /data/compactor
  shared_store: s3
  retention_enabled: true

analytics:
  reporting_enabled: false
