multitenancy_enabled: false

target: all

server:
  http_listen_port: 9090
  log_level: warn

blocks_storage:
  backend: s3
  s3:
    endpoint: minio:9000
    access_key_id: monitoring
    secret_access_key: supersecret
    insecure: true
    bucket_name: monitoring
  tsdb:
    dir: /data/tsdb

compactor:
  data_dir: /data/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

limits:
  compactor_blocks_retention_period: 90d

usage_stats:
  enabled: false
